# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.17.9" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.17.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.17.9.tgz";
        sha512 = "vqUSBLP8dQHFPdPi9bc5GK9vRkYHJ49fsZdtoJ8EQ8ibpwk5rPKfvNIwChB0KVXcIjcepEBBd2VHC5r9Gy8ueg==";
      };
    };
    "@types/linkify-it-3.0.2" = {
      name = "_at_types_slash_linkify-it";
      packageName = "@types/linkify-it";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/linkify-it/-/linkify-it-3.0.2.tgz";
        sha512 = "HZQYqbiFVWufzCwexrvh694SOim8z2d+xJl5UNamcvQFejLY/2YUtzXHYi3cHdI7PMlS8ejH2slRAOJQ32aNbA==";
      };
    };
    "@types/markdown-it-12.2.3" = {
      name = "_at_types_slash_markdown-it";
      packageName = "@types/markdown-it";
      version = "12.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/markdown-it/-/markdown-it-12.2.3.tgz";
        sha512 = "GKMHFfv3458yYy+v/N8gjufHO6MSZKCOXpZc5GXIWWy8uldwfmPn98vp81gZ5f9SVw8YYBctgfJ22a2d7AOMeQ==";
      };
    };
    "@types/mdurl-1.0.2" = {
      name = "_at_types_slash_mdurl";
      packageName = "@types/mdurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdurl/-/mdurl-1.0.2.tgz";
        sha512 = "eC4U9MlIcu2q0KQmXszyn5Akca/0jrQmwDRgpAMJai7qBWq4amIQhZyNau4VYGtCeALvW1/NtjzJJ567aZxfKA==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "catharsis-0.9.0" = {
      name = "catharsis";
      packageName = "catharsis";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/catharsis/-/catharsis-0.9.0.tgz";
        sha512 = "prMTQVpcns/tzFgFVkVp6ak6RykZyWb3gu8ckUpd6YkTlacOd3DXGJjIpD4Q6zJirizvaiAjSSHlOsA+6sNh2A==";
      };
    };
    "entities-2.1.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.1.0.tgz";
        sha512 = "hCx1oky9PFrJ611mf0ifBLBRW8lUUVRlFolb5gWRfIELabBlbp9xZvrqZLZAs+NxFnbfQoeGd8wDkygjg7U85w==";
      };
    };
    "escape-string-regexp-2.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
        sha512 = "UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
      };
    };
    "js2xmlparser-4.0.2" = {
      name = "js2xmlparser";
      packageName = "js2xmlparser";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-4.0.2.tgz";
        sha512 = "6n4D8gLlLf1n5mNLQPRfViYzu9RATblzPEtm1SthMX1Pjao0r9YI9nw7ZIfRxQMERS87mcswrg+r/OYrPRX6jA==";
      };
    };
    "jsdoc-3.6.10" = {
      name = "jsdoc";
      packageName = "jsdoc";
      version = "3.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsdoc/-/jsdoc-3.6.10.tgz";
        sha512 = "IdQ8ppSo5LKZ9o3M+LKIIK8i00DIe5msDvG3G81Km+1dhy0XrOWD0Ji8H61ElgyEj/O9KRLokgKbAM9XX9CJAg==";
      };
    };
    "klaw-4.0.1" = {
      name = "klaw";
      packageName = "klaw";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-4.0.1.tgz";
        sha512 = "pgsE40/SvC7st04AHiISNewaIMUbY5V/K8b21ekiPiFoYs/EYSdsGa+FJArB1d441uq4Q8zZyIxvAzkGNlBdRw==";
      };
    };
    "linkify-it-3.0.3" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-3.0.3.tgz";
        sha512 = "ynTsyrFSdE5oZ/O9GEf00kPngmOfVwazR5GKDq6EYfhlpFug3J2zybX56a2PRRpc9P+FuSoGNAwjlbDs9jJBPQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "markdown-it-12.3.2" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "12.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-12.3.2.tgz";
        sha512 = "TchMembfxfNVpHkbtriWltGWc+m3xszaRD0CZup7GFFhzIgQqxIfn3eGj1yZpfuflzPvfkt611B2Q/Bsk1YnGg==";
      };
    };
    "markdown-it-anchor-8.6.2" = {
      name = "markdown-it-anchor";
      packageName = "markdown-it-anchor";
      version = "8.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it-anchor/-/markdown-it-anchor-8.6.2.tgz";
        sha512 = "JNaekTlIwwyYGBN3zifZDxgz4bSL8sbEj58fdTZGmPSMMGXBZapFjcZk2I33Jy79c1fvCKHpF7MA/67FOTjvzA==";
      };
    };
    "marked-4.0.14" = {
      name = "marked";
      packageName = "marked";
      version = "4.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-4.0.14.tgz";
        sha512 = "HL5sSPE/LP6U9qKgngIIPTthuxC0jrfxpYMZ3LdGDD3vTnLs59m2Z7r6+LNDR3ToqEQdkKd6YaaEfJhodJmijQ==";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha1 = "75e75a96506611eb1c65ba89018ff08a981e2c16";
      };
    };
    "requizzle-0.2.3" = {
      name = "requizzle";
      packageName = "requizzle";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/requizzle/-/requizzle-0.2.3.tgz";
        sha512 = "YanoyJjykPxGHii0fZP0uUPEXpvqfBDxWV7s6GKAiiOsiqhX6vHNyW3Qzdmqp/iq/ExbhaGbVrjB4ruEVSM4GQ==";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "taffydb-2.6.2" = {
      name = "taffydb";
      packageName = "taffydb";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/taffydb/-/taffydb-2.6.2.tgz";
        sha1 = "7cbcb64b5a141b6a2efc2c5d2c67b4e150b2a268";
      };
    };
    "uc.micro-1.0.6" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.6.tgz";
        sha512 = "8Y75pvTYkLJW2hWQHXxoqRgV7qb9B+9vFEtidML+7koHUFapnVJAZ6cKs+Qjz5Aw3aZWHMC6u0wJE3At+nSGwA==";
      };
    };
    "underscore-1.13.2" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.13.2.tgz";
        sha512 = "ekY1NhRzq0B08g4bGuX4wd2jZx5GnKz6mKSqFL4nqBlfyMGiG10gDFhDTMEfYmDL6Jy0FUIZp7wiRB+0BP7J2g==";
      };
    };
    "xmlcreate-2.0.4" = {
      name = "xmlcreate";
      packageName = "xmlcreate";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlcreate/-/xmlcreate-2.0.4.tgz";
        sha512 = "nquOebG4sngPmGPICTS5EnxqhKbCmz5Ox5hsszI2T6U5qdrJizBc+0ilYSEjTSzU0yZcmvppztXe/5Al5fUwdg==";
      };
    };
  };
  args = {
    name = "nijs";
    packageName = "nijs";
    version = "0.0.25";
    src = ./.;
    dependencies = [
      sources."@babel/parser-7.17.9"
      sources."@types/linkify-it-3.0.2"
      sources."@types/markdown-it-12.2.3"
      sources."@types/mdurl-1.0.2"
      sources."argparse-2.0.1"
      sources."bluebird-3.7.2"
      sources."catharsis-0.9.0"
      sources."entities-2.1.0"
      sources."escape-string-regexp-2.0.0"
      sources."js2xmlparser-4.0.2"
      sources."jsdoc-3.6.10"
      sources."klaw-4.0.1"
      sources."linkify-it-3.0.3"
      sources."lodash-4.17.21"
      sources."markdown-it-12.3.2"
      sources."markdown-it-anchor-8.6.2"
      sources."marked-4.0.14"
      sources."mdurl-1.0.1"
      sources."mkdirp-1.0.4"
      sources."optparse-1.0.5"
      sources."requizzle-0.2.3"
      sources."slasp-0.0.4"
      sources."strip-json-comments-3.1.1"
      sources."taffydb-2.6.2"
      sources."uc.micro-1.0.6"
      sources."underscore-1.13.2"
      sources."xmlcreate-2.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An internal DSL for the Nix package manager in JavaScript";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
