# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.8.8" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.8.8.tgz";
        sha512 = "mO5GWzBPsPf6865iIbzNE0AvkKF3NE+2S3eRUpE+FE07BOAkXh6G+GW/Pj01hhXjve1WScbaIO4UlY1JKeqCcA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "catharsis-0.8.11" = {
      name = "catharsis";
      packageName = "catharsis";
      version = "0.8.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/catharsis/-/catharsis-0.8.11.tgz";
        sha512 = "a+xUyMV7hD1BrDQA/3iPV7oc+6W26BgVJO05PGEoatMyIuPScQKsde6i3YorWX1qs+AZjnJ18NqdKoCtKiNh1g==";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "escape-string-regexp-2.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
        sha512 = "UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
      };
    };
    "graceful-fs-4.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.3.tgz";
        sha512 = "a30VEBm4PEdx1dRB7MFK7BejejvCvBronbLjht+sHuGYj8PHs7M/5Z+rt5lw551vZ7yfTCj4Vuyy3mSJytDWRQ==";
      };
    };
    "js2xmlparser-4.0.1" = {
      name = "js2xmlparser";
      packageName = "js2xmlparser";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-4.0.1.tgz";
        sha512 = "KrPTolcw6RocpYjdC7pL7v62e55q7qOMHvLX1UCLc5AAS8qeJ6nukarEJAF2KL2PZxlbGueEbINqZR2bDe/gUw==";
      };
    };
    "jsdoc-3.6.3" = {
      name = "jsdoc";
      packageName = "jsdoc";
      version = "3.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsdoc/-/jsdoc-3.6.3.tgz";
        sha512 = "Yf1ZKA3r9nvtMWHO1kEuMZTlHOF8uoQ0vyo5eH7SQy5YeIiHM+B0DgKnn+X6y6KDYZcF7G2SPkKF+JORCXWE/A==";
      };
    };
    "klaw-3.0.0" = {
      name = "klaw";
      packageName = "klaw";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-3.0.0.tgz";
        sha512 = "0Fo5oir+O9jnXu5EefYbVK+mHMBeEVEy2cmctR1O1NECcCkPRreJKrS6Qt/j3KC2C148Dfo9i3pCmCMsdqGr0g==";
      };
    };
    "linkify-it-2.2.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-2.2.0.tgz";
        sha512 = "GnAl/knGn+i1U/wjBz3akz2stz+HrHLsxMwHQGofCDfPvlf+gDKN58UtfmUquTY4/MXeE2x7k19KQmeoZi94Iw==";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "markdown-it-8.4.2" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "8.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-8.4.2.tgz";
        sha512 = "GcRz3AWTqSUphY3vsUqQSFMbgR38a4Lh3GWlHRh/7MRwz8mcu9n2IO7HOh+bXHrR9kOPDl5RNCaEsrneb+xhHQ==";
      };
    };
    "markdown-it-anchor-5.2.5" = {
      name = "markdown-it-anchor";
      packageName = "markdown-it-anchor";
      version = "5.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it-anchor/-/markdown-it-anchor-5.2.5.tgz";
        sha512 = "xLIjLQmtym3QpoY9llBgApknl7pxAcN3WDRc2d3rwpl+/YvDZHPmKscGs+L6E05xf2KrCXPBvosWt7MZukwSpQ==";
      };
    };
    "marked-0.7.0" = {
      name = "marked";
      packageName = "marked";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.7.0.tgz";
        sha512 = "c+yYdCZJQrsRjTPhUx7VKkApw9bwDkNbHUKo1ovgcfDjb2kc8rLuRbIFyXL5WOEUwzSSKo3IXpph2K6DqB/KZg==";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha1 = "75e75a96506611eb1c65ba89018ff08a981e2c16";
      };
    };
    "requizzle-0.2.3" = {
      name = "requizzle";
      packageName = "requizzle";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/requizzle/-/requizzle-0.2.3.tgz";
        sha512 = "YanoyJjykPxGHii0fZP0uUPEXpvqfBDxWV7s6GKAiiOsiqhX6vHNyW3Qzdmqp/iq/ExbhaGbVrjB4ruEVSM4GQ==";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "strip-json-comments-3.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.0.1.tgz";
        sha512 = "VTyMAUfdm047mwKl+u79WIdrZxtFtn+nBxHeb844XBQ9uMNTuTHdx2hc5RiAJYqwTj3wc/xe5HLSdJSkJ+WfZw==";
      };
    };
    "taffydb-2.6.2" = {
      name = "taffydb";
      packageName = "taffydb";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/taffydb/-/taffydb-2.6.2.tgz";
        sha1 = "7cbcb64b5a141b6a2efc2c5d2c67b4e150b2a268";
      };
    };
    "uc.micro-1.0.6" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.6.tgz";
        sha512 = "8Y75pvTYkLJW2hWQHXxoqRgV7qb9B+9vFEtidML+7koHUFapnVJAZ6cKs+Qjz5Aw3aZWHMC6u0wJE3At+nSGwA==";
      };
    };
    "underscore-1.9.2" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.9.2.tgz";
        sha512 = "D39qtimx0c1fI3ya1Lnhk3E9nONswSKhnffBI0gME9C99fYOkNi04xs8K6pePLhvl1frbDemkaBQ5ikWllR2HQ==";
      };
    };
    "xmlcreate-2.0.3" = {
      name = "xmlcreate";
      packageName = "xmlcreate";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlcreate/-/xmlcreate-2.0.3.tgz";
        sha512 = "HgS+X6zAztGa9zIK3Y3LXuJes33Lz9x+YyTxgrkIdabu2vqcGOWwdfCpf1hWLRrd553wd4QCDf6BBO6FfdsRiQ==";
      };
    };
  };
  args = {
    name = "nijs";
    packageName = "nijs";
    version = "0.0.25";
    src = ./.;
    dependencies = [
      sources."@babel/parser-7.8.8"
      sources."argparse-1.0.10"
      sources."bluebird-3.7.2"
      sources."catharsis-0.8.11"
      sources."entities-1.1.2"
      sources."escape-string-regexp-2.0.0"
      sources."graceful-fs-4.2.3"
      sources."js2xmlparser-4.0.1"
      sources."jsdoc-3.6.3"
      sources."klaw-3.0.0"
      sources."linkify-it-2.2.0"
      sources."lodash-4.17.15"
      sources."markdown-it-8.4.2"
      sources."markdown-it-anchor-5.2.5"
      sources."marked-0.7.0"
      sources."mdurl-1.0.1"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."optparse-1.0.5"
      sources."requizzle-0.2.3"
      sources."slasp-0.0.4"
      sources."sprintf-js-1.0.3"
      sources."strip-json-comments-3.0.1"
      sources."taffydb-2.6.2"
      sources."uc.micro-1.0.6"
      sources."underscore-1.9.2"
      sources."xmlcreate-2.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An internal DSL for the Nix package manager in JavaScript";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}