# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  underscore = nodeEnv.buildNodePackage {
    name = "underscore";
    packageName = "underscore";
    version = "1.13.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/underscore/-/underscore-1.13.2.tgz";
      sha512 = "ekY1NhRzq0B08g4bGuX4wd2jZx5GnKz6mKSqFL4nqBlfyMGiG10gDFhDTMEfYmDL6Jy0FUIZp7wiRB+0BP7J2g==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript's functional programming helper library.";
      homepage = "https://underscorejs.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
